
pod:
  isTtyEnabled: true
  isStdinEnabled: true
  resources:
    cpu:
      limit: 4
      request: 1
    memory:
      limit: 8192Mi
      request: 512Mi

service: 
  ports:
    beacon:
      external: 32501
      local: 15000
    query:
      external: 32500
      local: 15777
    game:
      external: 32502
      local: 7777

image:
  name: wolveix/satisfactory-server
  tag: latest