apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
  - port: {{ .Values.service.ports.query.local }}
    nodePort: {{ .Values.service.ports.query.external }}
    protocol: UDP
    name: "query"
    targetPort: "query"
  - port: {{ .Values.service.ports.beacon.local }}
    nodePort: {{ .Values.service.ports.beacon.external }}
    protocol: UDP
    name: "beacon"
    targetPort: "beacon"
  - port: {{ .Values.service.ports.game.local }}
    nodePort: {{ .Values.service.ports.game.external }}
    protocol: UDP
    name: "game"
    targetPort: "game"
  selector:
    app: {{ .Release.Name }}